---
  - name: UNITTEST
    hosts: netscaler
    connection: local
    gather_facts: False

    tasks:
      - name: SAVE NETSACLER RUNNING CONFIG - CHANGE
        netscaler_save_config:
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"

      - name: SAVE NETSACLER RUNNING CONFIG NO HOST - FAIL
        netscaler_save_config:
          username: "{{ username }}"
          password: "{{ password }}"
        ignore_errors: true
